/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: (typeof import('./src/components/ui/card/Card.vue'))['default']
    CardContent: (typeof import('./src/components/ui/card/CardContent.vue'))['default']
    CardDescription: (typeof import('./src/components/ui/card/CardDescription.vue'))['default']
    CardFooter: (typeof import('./src/components/ui/card/CardFooter.vue'))['default']
    CardHeader: (typeof import('./src/components/ui/card/CardHeader.vue'))['default']
    CardTitle: (typeof import('./src/components/ui/card/CardTitle.vue'))['default']
    CharacterCard: typeof import('./src/components/CharacterCard.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    PaginationEllipsis: typeof import('./src/components/ui/pagination/PaginationEllipsis.vue')['default']
    PaginationFirst: typeof import('./src/components/ui/pagination/PaginationFirst.vue')['default']
    PaginationLast: typeof import('./src/components/ui/pagination/PaginationLast.vue')['default']
    PaginationNext: typeof import('./src/components/ui/pagination/PaginationNext.vue')['default']
    PaginationPrev: typeof import('./src/components/ui/pagination/PaginationPrev.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./src/components/ui/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./src/components/ui/scroll-area/ScrollBar.vue')['default']
    Separator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    Sheet: typeof import('./src/components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./src/components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./src/components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./src/components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./src/components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./src/components/ui/sheet/SheetHeader.vue')['default']
    SheetTitle: typeof import('./src/components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./src/components/ui/sheet/SheetTrigger.vue')['default']
    Skeleton: typeof import('./src/components/ui/skeleton/Skeleton.vue')['default']
  }
}
