/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sheet: typeof import('./src/components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./src/components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./src/components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./src/components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./src/components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./src/components/ui/sheet/SheetHeader.vue')['default']
    SheetTitle: typeof import('./src/components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./src/components/ui/sheet/SheetTrigger.vue')['default']
  }
}
